name: 13 - caching.yaml

on:
  workflow_dispatch:
    inputs:
      cache:
        description: 'Cache dependencies'
        type: boolean
        required: true
        default: true

      node-version:
        description: 'Node.js version'
        type: choice
        options:
          - '18.x'
          - '20.x'
          - '22.x'
        required: false
        default: '20.x'

jobs:

    build-app:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: 13-caching/react-app
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: ${{inputs.node-version}}

        - name: Cache node modules
          uses: actions/cache@v3
          if: ${{ inputs.cache }}
          id: cache-node-modules
          with:
            path: 13-caching/react-app/node_modules
            key: ${{ runner.os }}-node-${{ hashFiles('13-caching/react-app/package-lock.json') }}

        - name: Install dependencies
          run: npm ci

        - name: Test application
          run: npm test
        
        - name: Build application
          run: npm run build

        - name: Deploy application
          run: echo "Deploying application..."


            